steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_PATH}:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_PATH}:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-site'
      - '--image'
      - '${_IMAGE_PATH}:latest'
      - '--region'
      - '${_REGION}'
      - '-platform managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-central2
  _IMAGE_PATH: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/main/my-site-image

images:
  - '${_IMAGE_PATH}:latest'