steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/main/${_IMAGE_NAME}:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/main/${_IMAGE_NAME}:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-site'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/main/${_IMAGE_NAME}:latest'
      - '--region'
      - '${_REGION}'
      - '--platform' #default
      - 'managed' #default
      - '--allow-unauthenticated'
      - '--min-instances' #default
      - '0' #default
      - '--max-instances'
      - '5'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-central2
  _IMAGE_NAME: my-site-image
  #_IMAGE_PATH: europe-central2-docker.pkg.dev/${PROJECT_ID}/main/my-site-image

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/main/${_IMAGE_NAME}:latest'